# catches: the example ships no diagram, a stale/old-model diagram, or one not regenerated by the new
#          container renderer. Greps the committed diagram for the container model + absence of done_, and
#          confirms `graph --check` reports up-to-date against the freshly-built CLI.
$diagram = "docs/plans/09-preflight-first-class/example/diagram.md"
if (-not (Test-Path $diagram)) {
    Write-Output "$diagram does not exist - the example diagram was not generated (run `graph` against the local CLI)"
    exit 1
}
$content = Get-Content $diagram -Raw
if ($content -notmatch '(?i)subgraph' -or $content -notmatch '(?i)anchor') {
    Write-Output "$diagram is not the container model (no container subgraphs / invisible anchors) - regenerate with the new renderer"
    exit 1
}
if ($content -match 'done_') {
    Write-Output "$diagram still contains done_ reconvergence nodes - it was rendered by the old model"
    exit 1
}
$out = dotnet run --project src/Guardrails.Cli -c Debug -- graph docs/plans/09-preflight-first-class/example --check 2>&1
$out | ForEach-Object { Write-Output $_ }
if ($LASTEXITCODE -ne 0) {
    Write-Output "graph --check reports the example diagram is stale (exit $LASTEXITCODE) - regenerate example/diagram.md with the freshly-built CLI"
    exit 1
}
exit 0
